### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  car7: 192.168.124.107
  car10: 192.168.124.110

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
- topic_name: /car7/cmd_vel # send the messages of this ROS topic
  msg_type: geometry_msgs/Twist # ROS message type (rosmsg style)
  max_freq: 100 # max send frequency (Hz) int
  srcIP: self # self IP
  srcPort: 3001 # ports of send_topics should be different

- topic_name: /car10/cmd_vel
  msg_type: geometry_msgs/Twist
  max_freq: 100
  srcIP: self
  srcPort: 3002

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
- topic_name: /car7/imu # the received messages will be published in this topic
  msg_type: sensor_msgs/Imu # ROS message type (rosmsg style)
  srcIP: car7 # message source IPname
  srcPort: 3001 # message source port

- topic_name: /car10/imu # the received messages will be published in this topic
  msg_type: sensor_msgs/Imu # ROS message type (rosmsg style)
  srcIP: car10 # message source IPname
  srcPort: 3001 # message source port
